AndroidAppautomationName=UiAutomator2
AndroidAppPackageName=com.xometry.workcenter.preview.stage
AndroidAppActivityName=com.xometry.workcenter.preview.stage.MainActivity
AppiumURL=http://127.0.0.1:4723/wd/hub
